-- Docs:
-- - artifacts/docs/data/3. Шаги выполнения checklist.md
-- - artifacts/docs/data/2.0 Стандарт разработки (рабочий, Lite).md
-- - artifacts/docs/datastand/0.2.4 log_work_chaitan_mashine.md

GRANT USAGE ON SCHEMA raw, stg, mon, mart TO :"AIRFLOW_USER";
GRANT USAGE ON SCHEMA stg, mart TO :"PROJECT_USER";

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA raw TO :"AIRFLOW_USER";
GRANT SELECT ON ALL TABLES IN SCHEMA stg TO :"AIRFLOW_USER";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mon TO :"AIRFLOW_USER";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mart TO :"AIRFLOW_USER";
GRANT SELECT ON ALL TABLES IN SCHEMA stg TO :"PROJECT_USER";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mart TO :"PROJECT_USER";

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA raw TO :"AIRFLOW_USER";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA stg TO :"AIRFLOW_USER";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA mon TO :"AIRFLOW_USER";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA mart TO :"AIRFLOW_USER";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA stg TO :"PROJECT_USER";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA mart TO :"PROJECT_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA raw
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA stg
GRANT SELECT ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA mon
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA mart
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA mart
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"PROJECT_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA raw
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA stg
GRANT USAGE, SELECT ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA mon
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA mart
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA mart
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"PROJECT_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA raw
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA stg
GRANT SELECT ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA mon
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA mart
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA stg
GRANT SELECT ON TABLES TO :"PROJECT_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA stg
GRANT SELECT ON TABLES TO :"PROJECT_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA raw
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA stg
GRANT USAGE, SELECT ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA mon
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA mart
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"AIRFLOW_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"PROJECT_USER" IN SCHEMA stg
GRANT USAGE, SELECT ON SEQUENCES TO :"PROJECT_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA stg
GRANT USAGE, SELECT ON SEQUENCES TO :"PROJECT_USER";
